export const ERROR_MESSAGES = {
    // Common
    "Login not found": "Usuário não encontrado",
    "User is not active": "Usuário não está ativo",
    "Invalid login or password": "Login ou senha inválidos",
    "Name is required": "Nome é obrigatório",
    "Login is required": "Login é obrigatório",
    "Email is required": "Email é obrigatório",
    "Password should be at least 8 characters long": "Senha deve ter pelo menos 8 caracteres",
    "Invalid email format": "Formato de email inválido",
    "Company is required": "Empresa é obrigatória",
    "User with this email already exists": "Usuário com este email já existe",
    "Empresa not found": "Empresa não encontrada",
    "User with this login already exists": "Usuário com este login já existe",
    "CPF already exists": "CPF já existe",
    "CNPJ already exists": "CNPJ já existe",
    "Email already exists": "Email já existe",
    "Customer not found": "Cliente não encontrado",
    "Company id is required": "Empresa é obrigatória",
    "Product already exists": "Já existe um produto com este código",
    "Order number already exists": "Já existe uma venda com este número",
    "Product not found": "Produto não encontrado",
    "Insufficient inventory for product": "Estoque insuficiente para o produto",
    "Missing orderId": "Falta o id da venda",
    "Order not found": "Venda não encontrada",
    "One or more products are missing codigo_ncm": "Um ou mais produtos estão sem código NCM",
    "Missing nome": "Falta o nome",
    "Missing nome_fantasia": "Falta o nome fantasia",
    "Code is required": "Código interno é obrigatório",
    "id not found": "Id não encontrado",
    "statusId not found": "Status não encontrado",
    "Id is required": "Id é obrigatório",
};
